name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: |
          python -m pip install -U pip
          python -m pip install --use-pep517 '.[dev]'
      - run: make test_coverage
        env:
          PYTHONWARNINGS: default

  coverage_report:
    if: github.ref_name == 'master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: make coverage_report
      - uses: actions/upload-pages-artifact@v2
        with:
          path: htmlcov

  deploy:
    if: github.ref_name == 'master'
    needs: coverage_report
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v3
